spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sistematrocas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPostgresDev
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update